//
//  Attachment.swift
//  Chica
//
//  Created by Marquis Kurt on 7/7/20.
//

import Foundation

/// A media attachment from a post or other content.
public struct MediaAttachment: Codable, Identifiable {
    /// The ID associated with this attachment registered with the server.
    public let id: String

    /// The type of attachment.
    public let type: AttachmentType

    /// The attachment's website URL.
    public let url: String

    /// The attachment's website URL to remote content.
    public let remoteURL: String?

    /// The attachment's website URL to the remote content's preview.
    public let previewURL: String?

    /// The attachment's website URL to text.
    @available(*, deprecated, message: "Removed in Mastodon v3.5.0. Use MediaAttachment.url instead.")
    public let textURL: String?

    /// The attachment's description.
    public let description: String?

    /// A hash generated by the BlurHash algorithm used for creating thumbnails.
    public let blurhash: String

    // MARK: - Coding Keys

    private enum CodingKeys: String, CodingKey {
        case id
        case type
        case url
        case remoteURL = "remote_url"
        case previewURL = "preview_url"
        case textURL = "text_url"
        case description
        case blurhash
    }
}

/// Grants us conformance to `Hashable` for _free_
extension MediaAttachment: Hashable {
    public static func == (lhs: MediaAttachment, rhs: MediaAttachment) -> Bool {
        return lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}
