name: Run Unit Tests

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0-beta'
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
