name: Run Unit Tests

on:
  pull_request:
    branches: [ root, devel ]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Danger
      uses: danger/swift@2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
