name: Deploy FlowKit Docs

on:
  push:
    branches: [ root, devel ]
  pull_request:
    branches: [ root, devel ]
  workflow_dispatch:

jobs:
  docc:
    name: DocC Deployment
    runs-on: macos-13
    steps:
    - name: Setup Xcode 15
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '15.0-beta'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Documentation
      run: |
        cd Packages/FlowKit
        swift test
