name: Deploy FlowKit Docs

on:
  push:
    branches: [ root, devel ]
  workflow_dispatch:

jobs:
  docc:
    name: DocC Deployment
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Documentation
      run: |
        cd Packages/FlowKit
        swift test
